### ISSUE TITLE
Dark menu text on GNOME 3.34

### ISSUE THREAD

**Issue by Gruven** [EliverLara/Ant-Dracula#25] opened 2019-10-28 07:11 UTC
I've just updated to Ubuntu 19.10 and now most menus in taskbar has dart text on dark background. Can we fix this?
![Снимок экрана от 2019-10-28 12-07-20](https://user-images.githubusercontent.com/410058/67658550-b4bba200-f97b-11e9-8030-dd05995b7a3f.png)
![Снимок экрана от 2019-10-28 12-07-31](https://user-images.githubusercontent.com/410058/67658554-b8e7bf80-f97b-11e9-9fcf-34aa78220310.png)
![Снимок экрана от 2019-10-28 12-09-24](https://user-images.githubusercontent.com/410058/67658583-d3ba3400-f97b-11e9-936f-143801cdb8f6.png)
![Снимок экрана от 2019-10-28 12-09-12](https://user-images.githubusercontent.com/410058/67658589-d74dbb00-f97b-11e9-8fd2-785f876845a3.png)

**Comment by nathaniades** [comment] 2019-11-04 13:02
Issue persists, Ubuntu 19.10. Visible in the right click menu. The current fix is to simply change my shell theme to default.
![Screenshot from 2019-11-04 14-59-09](https://user-images.githubusercontent.com/57148132/68122805-dab0eb80-ff13-11e9-8ade-eb5a95ab4256.png)

**Comment by EliverLara** [comment] 2019-11-04 17:00
@Gruven @nathaniades Could you test if it was fixed with the last commit, please?

**Comment by nathaniades** [comment] 2019-11-04 17:45
I can confirm that the problem is fixed. 
![Screenshot from 2019-11-04 19-43-45](https://user-images.githubusercontent.com/57148132/68144089-8f123800-ff3b-11e9-8589-666225e99924.png)
Thank you!

**Comment by Gruven** [comment] 2019-11-05 04:50
@EliverLara everything seems to be fine. Thanks!

**Closed** 2019-11-05 04:50 UTC
